### PR TITLE
#167613413 Integrate code climate

### PR DESCRIPTION
**Pull request by Jaman-dedy**
## Description ##
Integrate code climate with the backend repository and add the Code climate Badge in the Readme file. 

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of a feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test
- [x] None

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[#167613413](https://www.pivotaltracker.com/story/show/167613413)

### CODE REVIEW

**Review by MandelaK — APPROVED** [review]

**Review by Victoradukwu — APPROVED** [review]

**Review by akram256 — APPROVED** [review]
LGTM

**Review by JamesMudidi — APPROVED** [review]
LGTM

**Comment by Tevinthuku** [comment]
It's weird how these tests are failing on functionality you did not create. 

image
Is there a way this can be solved?

**Review by kdaglas — APPROVED** [review]
LGTM

**Pull request merged**
