### PR TITLE
#165826464 disable user's ability to download pictures

### PR DESCRIPTION
**Pull request by alexxsanya**
## Description ##
- disable users from downloading images/pictures from the site

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of a feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

## How to test this PR
- Visit the [App](https://landville-frontend-pr-31.herokuapp.com/) here
- When you right-click the pictures on the various pages of the app, you should not have the options to save them off the site.

## Related Pivotal Tracker stories ##
[#165826464](https://www.pivotaltracker.com/story/show/165826464)

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
Works as expected, good job @alexxsanya

**Review by patrickf949 — APPROVED** [review]
LGTM

**Review by Manorlds-Eaglespark — APPROVED** [review]
Works as expected.

**Review by wangonya — COMMENTED** [review]
LGTM

**Review by neelxie — APPROVED** [review]
LGTM

**Review by shemaeric — APPROVED** [review]
LGTM

**Review by kdaglas — APPROVED** [review]
This is good though it's really short, there are some more ways of disabling the ability to download pictures, but I have tested it and its ok.

**Review by CryceTruly — APPROVED** [review]
This is incredibly done @alexxsanya, Keep It Up.
LGTM 💯

**Review by Victoradukwu — APPROVED** [review]
Works as expected

**Pull request merged**
